// Code generated by mygrate; DO NOT EDIT.
// 2019-03-12 21:15:19.7956271 +0100 CET m=+0.005029501

// Package mygrations provides the migration files for the project
package mygrations

import (
	"github.com/stahlstift/go-mygrate/pkg/mygrate"
)

func Register(m *mygrate.Mygrate) {
	m.Register(1552420260, "init", Mygration_1552420260_init_Up, Mygration_1552420260_init_Down)
}

